name: Build Nova APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: android debug
          workdir: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nova-APK
          path: bin/*.apk
